#pragma once

#define CAPS_WORD_INVERT_ON_SHIFT
#define MASTER_RIGHT

#define COMBO_TERM 40

#define AUTO_SHIFT_MODIFIERS
#define AUTO_SHIFT_TIMEOUT 130
#define RETRO_SHIFT 200

// HOME ROW MODS
#define TAPPING_TERM 130
