//OLED_ENABLE = yes
//OLED_DRIVER = SSD1306      # Enables the use of OLED displays

REPEAT_KEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
SWAP_HANDS_ENABLE = yes
MOUSEKEY_ENABLE = yes

//ENCODER_ENABLE = yes
//ENCODER_MAP_ENABLE = yes

COMBO_ENABLE = yes
//VPATH += keyboards/gboards
MACROS_ENABLED = yes
